apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: cloudnotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14  # Use PostgreSQL version 14
        env:
        - name: POSTGRES_USER
          value: "clouduser"
        - name: POSTGRES_PASSWORD
          value: "cloudpass"
        - name: POSTGRES_DB
          value: "cloudnotes"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc  # Uses PVC for persistent data storage
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: cloudnotes
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432   # This is the correct PostgreSQL port
      targetPort: 5432
  type: ClusterIP  # Exposes PostgreSQL internally to the cluster
